# Data path. adjust them!
common:
    image_file: "/cv_project/data/calibration/image/0.png"
    pcd_file: "/cv_project/data/calibration/pcd/0.pcd"
    result_file: "/cv_project/catkin_ws/src/livox_camera_calib/result/extrinsic.txt"

# Camera Parameters. Adjust them!
camera:
    camera_matrix: [910.623, 0.0, 651.66,
      0.0,  910.183, 365.568,
      0.0, 0.0, 1.0 ]
    dist_coeffs: [0.0, 0.0, 0.0, 0.0, 0.0]

# Calibration Parameters.!
calib:
    calib_config_file: "/cv_project/catkin_ws/src/livox_camera_calib/config/config_indoor.yaml"
    use_rough_calib: false # set true if your initial_extrinsic is bad
