# Data path. adjust them!
common:
    image_path: "/cv_project/data/calibration/image"
    pcd_path: "/cv_project/data/calibration/pcd"
    result_path: "/cv_project/catkin_ws/src/livox_camera_calib/result/extrinsic.txt"
    data_num: 6
# Camera Parameters. Adjust them!
camera:
    camera_matrix: [910.623, 0.0, 651.66,
      0.0,  910.183, 365.568,
      0.0, 0.0, 1.0 ]
    dist_coeffs: [-0.0963, 0.0708, 0.0011, -0.0017, 0.000000]

# Calibration Parameters.!
calib:
    calib_config_file: "/cv_project/catkin_ws/src/livox_camera_calib/config/config_indoor.yaml"
    use_rough_calib: false # set true if your initial_extrinsic is bad
